#include "/home/codeleaded/System/Static/Container/Queue.h"
#include "/home/codeleaded/System/Static/Container/DataStream.h"
#include "/home/codeleaded/System/Static/Container/SQuadTree.h"
#include "/home/codeleaded/System/Static/Container/ShiftQueue.h"
#include "/home/codeleaded/System/Static/Container/Vector.h"
#include "/home/codeleaded/System/Static/Container/Algorithms.h"
#include "/home/codeleaded/System/Static/Container/MVector.h"
#include "/home/codeleaded/System/Static/Container/Bitfield.h"
#include "/home/codeleaded/System/Static/Container/LabeledArray.h"
#include "/home/codeleaded/System/Static/Container/Pair.h"
#include "/home/codeleaded/System/Static/Container/CVector.h"
#include "/home/codeleaded/System/Static/Container/PVector.h"
#include "/home/codeleaded/System/Static/Container/Tree.h"
#include "/home/codeleaded/System/Static/Container/Hashmap.h"
#include "/home/codeleaded/System/Static/Container/Heap.h"
#include "/home/codeleaded/System/Static/Container/Iterator.h"
#include "/home/codeleaded/System/Static/Container/BinTree.h"
#include "/home/codeleaded/System/Static/Container/Array.h"
#include "/home/codeleaded/System/Static/Container/Deque.h"
#include "/home/codeleaded/System/Static/Container/LayeredBuffer.h"
#include "/home/codeleaded/System/Static/Container/LVector.h"
#include "/home/codeleaded/System/Static/Container/Graph.h"
#include "/home/codeleaded/System/Static/Container/Dictionary.h"
#include "/home/codeleaded/System/Static/Container/List.h"
#include "/home/codeleaded/System/Static/Container/Stack.h"
#include "/home/codeleaded/System/Static/Container/WLArray.h"
#include "/home/codeleaded/System/Static/Container/Set.h"
#include "/home/codeleaded/System/Static/Container/Cast.h"
#include "/home/codeleaded/System/Static/Container/Database.h"

#include "/home/codeleaded/System/Static/Library/AlxFont.h"
#include "/home/codeleaded/System/Static/Library/CStr_G.h"
#include "/home/codeleaded/System/Static/Library/AStar.h"
#include "/home/codeleaded/System/Static/Library/Dom.h"
#include "/home/codeleaded/System/Static/Library/ComponentPack.h"
#include "/home/codeleaded/System/Static/Library/Files.h"
#include "/home/codeleaded/System/Static/Library/AlxCompiler.h"
#include "/home/codeleaded/System/Static/Library/Chess.h"
#include "/home/codeleaded/System/Static/Library/Line.h"
#include "/home/codeleaded/System/Static/Library/DD7Segment.h"
#include "/home/codeleaded/System/Static/Library/String.h"
#include "/home/codeleaded/System/Static/Library/Input.h"
#include "/home/codeleaded/System/Static/Library/Allocator.h"
#include "/home/codeleaded/System/Static/Library/Fixed.h"
#include "/home/codeleaded/System/Static/Library/NeuralNetwork.h"
#include "/home/codeleaded/System/Static/Library/AlxParser.h"
#include "/home/codeleaded/System/Static/Library/Math.h"
#include "/home/codeleaded/System/Static/Library/Console_Tools.h"
#include "/home/codeleaded/System/Static/Library/Integer.h"
#include "/home/codeleaded/System/Static/Library/MTG.h"
#include "/home/codeleaded/System/Static/Library/Ray.h"
#include "/home/codeleaded/System/Static/Library/Splines.h"
#include "/home/codeleaded/System/Static/Library/Circuit.h"
#include "/home/codeleaded/System/Static/Library/Tex.h"
#include "/home/codeleaded/System/Static/Library/ConvexShape.h"
#include "/home/codeleaded/System/Static/Library/FSystem.h"
#include "/home/codeleaded/System/Static/Library/Sprite.h"
#include "/home/codeleaded/System/Static/Library/Geometry.h"
#include "/home/codeleaded/System/Static/Library/Vdctor2.h"
#include "/home/codeleaded/System/Static/Library/VBLikeDefines.h"
#include "/home/codeleaded/System/Static/Library/SoundBoard.h"
#include "/home/codeleaded/System/Static/Library/AlxScope.h"
#include "/home/codeleaded/System/Static/Library/DLL.h"
#include "/home/codeleaded/System/Static/Library/Regex.h"
#include "/home/codeleaded/System/Static/Library/Char_G.h"
#include "/home/codeleaded/System/Static/Library/BigNumber.h"
#include "/home/codeleaded/System/Static/Library/Pixel.h"
#include "/home/codeleaded/System/Static/Library/AlxThrow.h"
#include "/home/codeleaded/System/Static/Library/Vector4.h"
#include "/home/codeleaded/System/Static/Library/WavePropagation.h"
#include "/home/codeleaded/System/Static/Library/IntegerSet.h"
#include "/home/codeleaded/System/Static/Library/ExcelRenderer.h"
#include "/home/codeleaded/System/Static/Library/Networking.h"
#include "/home/codeleaded/System/Static/Library/RealSet.h"
#include "/home/codeleaded/System/Static/Library/Vector2.h"
#include "/home/codeleaded/System/Static/Library/Analysis.h"
#include "/home/codeleaded/System/Static/Library/AlxExternFunctions.h"
#include "/home/codeleaded/System/Static/Library/Compare.h"
#include "/home/codeleaded/System/Static/Library/Int_Parser.h"
#include "/home/codeleaded/System/Static/Library/Clipboard.h"
#include "/home/codeleaded/System/Static/Library/Lib3D_Cube.h"
#include "/home/codeleaded/System/Static/Library/Image.h"
#include "/home/codeleaded/System/Static/Library/TheaterSystem.h"
#include "/home/codeleaded/System/Static/Library/RLCamera.h"
#include "/home/codeleaded/System/Static/Library/GarbageCollector.h"
#include "/home/codeleaded/System/Static/Library/PerlinNoise.h"
#include "/home/codeleaded/System/Static/Library/Component.h"
#include "/home/codeleaded/System/Static/Library/Triangle.h"
#include "/home/codeleaded/System/Static/Library/Random.h"
#include "/home/codeleaded/System/Static/Library/Rect.h"
#include "/home/codeleaded/System/Static/Library/AlxEnviroment.h"
#include "/home/codeleaded/System/Static/Library/ObjectNotationProto.h"
#include "/home/codeleaded/System/Static/Library/AlxCallStack.h"
#include "/home/codeleaded/System/Static/Library/Periodic.h"
#include "/home/codeleaded/System/Static/Library/Zip.h"
#include "/home/codeleaded/System/Static/Library/InteractionSystem.h"
#include "/home/codeleaded/System/Static/Library/Video.h"
#include "/home/codeleaded/System/Static/Library/InputKeyboard.h"
#include "/home/codeleaded/System/Static/Library/Stream.h"
#include "/home/codeleaded/System/Static/Library/Vector3.h"
#include "/home/codeleaded/System/Static/Library/IRDefines.h"
#include "/home/codeleaded/System/Static/Library/TextBox.h"
#include "/home/codeleaded/System/Static/Library/Victor2.h"
#include "/home/codeleaded/System/Static/Library/Audio.h"
#include "/home/codeleaded/System/Static/Library/AlxTime.h"
#include "/home/codeleaded/System/Static/Library/HttpServer.h"
#include "/home/codeleaded/System/Static/Library/DumperMap.h"
#include "/home/codeleaded/System/Static/Library/TString.h"
#include "/home/codeleaded/System/Static/Library/AlxWindow_Linux.h"
#include "/home/codeleaded/System/Static/Library/Poly.h"
#include "/home/codeleaded/System/Static/Library/Float.h"
#include "/home/codeleaded/System/Static/Library/LCG.h"
#include "/home/codeleaded/System/Static/Library/LuaLike.h"
#include "/home/codeleaded/System/Static/Library/Char.h"
#include "/home/codeleaded/System/Static/Library/GSprite.h"
#include "/home/codeleaded/System/Static/Library/AudioPlayer.h"
#include "/home/codeleaded/System/Static/Library/Point.h"
#include "/home/codeleaded/System/Static/Library/PS4_Controller.h"
#include "/home/codeleaded/System/Static/Library/Stroke.h"
#include "/home/codeleaded/System/Static/Library/Fluid.h"
#include "/home/codeleaded/System/Static/Library/AglWindow_Linux.h"
#include "/home/codeleaded/System/Static/Library/IRRuntime.h"
#include "/home/codeleaded/System/Static/Library/MenuSystem.h"
#include "/home/codeleaded/System/Static/Library/ImageFilter.h"
#include "/home/codeleaded/System/Static/Library/Thread.h"
#include "/home/codeleaded/System/Static/Library/Shell.h"
#include "/home/codeleaded/System/Static/Library/Types.h"
#include "/home/codeleaded/System/Static/Library/Bluetooth.h"
#include "/home/codeleaded/System/Static/Library/Circle.h"
#include "/home/codeleaded/System/Static/Library/ComponentML.h"
#include "/home/codeleaded/System/Static/Library/CircleLine.h"
#include "/home/codeleaded/System/Static/Library/AffineTransform.h"
#include "/home/codeleaded/System/Static/Library/Lib3D_Mathlib.h"
#include "/home/codeleaded/System/Static/Library/QueryLanguage.h"
#include "/home/codeleaded/System/Static/Library/Lib3D_Mesh.h"
#include "/home/codeleaded/System/Static/Library/LuaLikeDefines.h"
#include "/home/codeleaded/System/Static/Library/Excel.h"
#include "/home/codeleaded/System/Static/Library/String_G.h"
#include "/home/codeleaded/System/Static/Library/ObjectNotation.h"
#include "/home/codeleaded/System/Static/Library/AlxShutingYard.h"
#include "/home/codeleaded/System/Static/Library/DLS.h"
#include "/home/codeleaded/System/Static/Library/Wine.h"
#include "/home/codeleaded/System/Static/Library/Complex2.h"
#include "/home/codeleaded/System/Static/Library/RayCast.h"
#include "/home/codeleaded/System/Static/Library/IR.h"
#include "/home/codeleaded/System/Static/Library/ConstParser.h"
#include "/home/codeleaded/System/Static/Library/Graphics.h"
#include "/home/codeleaded/System/Static/Library/Scene.h"
#include "/home/codeleaded/System/Static/Library/AlxInterpreter.h"
#include "/home/codeleaded/System/Static/Library/TransformedView.h"
#include "/home/codeleaded/System/Static/Library/Intrinsics.h"
#include "/home/codeleaded/System/Static/Library/CStr.h"
#include "/home/codeleaded/System/Static/Library/VBLike.h"
#include "/home/codeleaded/System/Static/Library/Attributes.h"
#include "/home/codeleaded/System/Static/Library/OpticalFlow.h"
#include "/home/codeleaded/System/Static/Library/ComponentDefines.h"
#include "/home/codeleaded/System/Static/Library/Kryptography.h"
#include "/home/codeleaded/System/Static/Library/Pointer.h"

//#include "/home/codeleaded/System/Static/Library/TerminalCtl.h"
#include "/home/codeleaded/System/Static/Library/TerminalEngine.h"

//#include "/home/codeleaded/System/Static/Library/Signal.h"
// #include "/home/codeleaded/System/Static/Library/InputMouse.h"
// #include "/home/codeleaded/System/Static/Library/WindowEngineGL1.0.h"
// #include "/home/codeleaded/System/Static/Library/WindowEngine1.0.h"

// #include "/home/codeleaded/System/Static/Library/AlxWindow_Windows.h"

// #define STB_IMAGE_IMPLEMENTATION
// #include "/home/codeleaded/System/Static/Library/Stb_Image.h"
// #include "/home/codeleaded/System/Static/Library/Cmd.h"

//#include "/home/codeleaded/System/Static/Library/ConsoleEngine.h"
//#include "/home/codeleaded/System/Static/Library/WindowEngine.h"
//#include "/home/codeleaded/System/Static/Library/WindowEngine_Old.h"
//#include "/home/codeleaded/System/Static/Library/olcConsoleGameEngine.hpp"
//#include "/home/codeleaded/System/Static/Library/olcPixelGameEngine.hpp"


// #include "/home/codeleaded/System/Static/Library/Files.h"
// #include <stdio.h>

// void Walk(char* path){
// 	printf("%s\n",path);
// }

int main(int argc,char** argv){
	
	//Files_Walk("/home/codeleaded/System/Static/Container",Walk);

	return 0;
}
